apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: frontend
    project: expense
    component: frontend
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
  
